"""English editorial content and source-backed slide visuals."""
from html import escape
from base64 import b64encode
from pathlib import Path


def diagram(title, nodes, mode='flow'):
    """Concept diagram: relationships, never fabricated performance data."""
    if mode == 'hub':
        logo = b64encode((Path(__file__).resolve().parents[1] / 'site/public/images/logo.webp').read_bytes()).decode()
        shapes = f'<image href="data:image/webp;base64,{logo}" x="100" y="185" width="360" height="80" preserveAspectRatio="xMidYMid meet"/>'
        for i, ((x,y), text) in enumerate(zip([(20,35),(300,35),(20,315),(300,315)],nodes), 1):
            shapes += f'<rect x="{x}" y="{y}" width="240" height="100" rx="18" fill="white"/><text x="{x+22}" y="{y+30}" fill="#087fba" font-size="15">0{i}</text><text x="{x+22}" y="{y+70}" fill="#213d32" font-size="23">{escape(text)}</text>'
        return f'<figure class="visual-art"><svg viewBox="0 0 560 450" role="img" aria-label="{escape(title)}"><title>{escape(title)}</title>{shapes}</svg><figcaption>{escape(title)} · Concept diagram</figcaption></figure>'
    elif mode == 'branches':
        shapes = '<path d="M280 95 V140 M100 140 H460 M100 140 V195 M280 140 V195 M460 140 V195 M100 265 V330 H460 V265 M280 265 V360" fill="none" stroke="#8aa99a" stroke-width="3"/>'
        shapes += '<rect x="135" y="35" width="290" height="60" rx="14" fill="#17613f"/><text x="280" y="73" fill="white" font-size="23" text-anchor="middle">'+escape(nodes[0])+'</text>'
        for x,text in zip([100,280,460],nodes[1:4]):
            shapes += f'<rect x="{x-82}" y="195" width="164" height="70" rx="12" fill="#edf5fa"/><text x="{x}" y="235" text-anchor="middle" fill="#213d32" font-size="19">{escape(text)}</text>'
        shapes += '<rect x="135" y="360" width="290" height="60" rx="14" fill="#17613f"/><text x="280" y="398" fill="white" font-size="23" text-anchor="middle">'+escape(nodes[4])+'</text>'
    else:
        shapes = ''
        for i,text in enumerate(nodes):
            y=48+i*94
            if i: shapes += f'<path d="M280 {y-45} V{y-12}" stroke="#087fba" stroke-width="3" marker-end="url(#arrow)"/>'
            shapes += f'<rect x="55" y="{y}" width="450" height="65" rx="16" fill="{"#17613f" if i==len(nodes)-1 else "#edf5fa"}"/><circle cx="88" cy="{y+32}" r="18" fill="white"/><text x="88" y="{y+39}" text-anchor="middle" font-size="19" fill="#17613f">{i+1}</text><text x="125" y="{y+40}" font-size="24" fill="{"white" if i==len(nodes)-1 else "#213d32"}">{escape(text)}</text>'
    return f'<figure class="visual-art"><svg viewBox="0 0 560 450" role="img" aria-label="{escape(title)}"><title>{escape(title)}</title><defs><marker id="arrow" viewBox="0 0 10 10" refX="8" refY="5" markerWidth="6" markerHeight="6" orient="auto"><path d="M0 0 L10 5 L0 10" fill="#087fba"/></marker></defs>{shapes}</svg><figcaption>{escape(title)} · Concept diagram</figcaption></figure>'


def bars(title, values, total, caption):
    shapes='<line x1="180" y1="40" x2="180" y2="345" stroke="#a4b7ac"/>'
    for i,(label,value,color) in enumerate(values):
        y=65+i*92
        shapes += f'<text x="165" y="{y+27}" text-anchor="end" font-size="19" fill="#213d32">{escape(label)}</text><rect x="180" y="{y}" width="300" height="40" rx="5" fill="#e5eee7"/><rect class="chart-bar" x="180" y="{y}" width="{300*value/total}" height="40" rx="5" fill="{color}"/><text x="500" y="{y+28}" font-size="24" font-weight="bold" fill="#213d32">{value}</text>'
    shapes+=f'<text x="180" y="385" font-size="17" fill="#56645b">0</text><text x="480" y="385" text-anchor="end" font-size="17" fill="#56645b">{total} snapshots</text>'
    return f'<figure class="visual-art"><svg viewBox="0 0 560 430" role="img" aria-label="{escape(title)}"><title>{escape(title)}</title>{shapes}</svg><figcaption>{escape(caption)}</figcaption></figure>'


def populate(slide, photo, row):
    def page(label,title,lead,points,visual,note='Development proposal · Linc × Mecosin',cls=''):
        body='<div class="editorial"><div class="talking-points">'+''.join(row(f'{i+1:02}',h,t) for i,(h,t) in enumerate(points))+'</div><div class="art-panel">'+visual+'</div></div>'
        slide(label,title,lead,body,cls=cls,note=note)
    def image(name,alt,caption):
        return '<figure class="visual-art photo-art">'+photo(name,alt)+'<figcaption>'+caption+'</figcaption></figure>'
    page('Platform revamp pitch','Mecosin website proposal:<br>product sales and B2B enquiries','A website that helps people understand products and helps partners start a conversation.',
        [('Herbal heritage. Digital opportunity.','A platform revamp proposal for stronger discovery, customer confidence and business enquiries.'),('One platform, two audiences','Clear journeys for consumers and prospective business partners.')],image('botanical.webp','Botanical arrangement from Mecosin assets','Herbal heritage / digital opportunity'),cls='opening')
    page('01 / Platform strategy','Use the website to sell products<br>and attract business partners.','Connect product education, partner discovery and customer relationships.',
        [('Reach business partners','Make capabilities and partnership opportunities easier to evaluate.'),('Support consumer decisions','Help visitors find products, understand information and choose a purchase channel.'),('Build direct relationships','Develop an owned channel for content, enquiries and repeat engagement.')],diagram('Four connected business goals',['B2B reach','Consumer sales','Brand trust','Owned channel'],'hub'))
    page('02 / Audience journeys','Separate shopping<br>from partnership enquiries.','Separate consumer and business needs from the homepage, with mobile-first navigation.',
        [('Consumer journey','Explore needs, read approved product information, get answers and find a purchase channel.'),('Partner journey','Review capabilities, explore partnership models, download a profile and submit an enquiry.')],diagram('Audience routing',['Homepage','Consumers / Business partners','Product / Capability information','Purchase channel / Enquiry']))
    page('03 / Search & discovery','SEO helps customers find<br>Mecosin through Google.','SEO (search engine optimization) helps Google find and understand pages so people can discover them in unpaid search results.',
        [('Make pages discoverable','Fix links, indexing and sitemaps; give each page a clear title and useful content. Health content needs qualified review.'),('Bring relevant visitors to Mecosin','Product searches can lead to official information and shopping; manufacturing searches can lead to B2B enquiries.'),('Measure business value','Track organic clicks in Search Console and enquiries or sales in analytics. No per-click ad charge, but SEO needs work; rankings and sales are not guaranteed.')],'<figure class="visual-art search-art"><span class="mock-label">ILLUSTRATIVE SEARCH JOURNEY</span><div class="search-box">herbal manufacturer Indonesia <span>⌕</span></div><div class="result"><small>Official capability page</small><h3>Mecosin | Partnership opportunities</h3><p>Capabilities, verified documentation and a clear enquiry path.</p></div><div class="search-link">Search intent → Relevant page → Enquiry</div><figcaption>Concept only · not an observed search ranking</figcaption></figure>')
    page('SEO / How search works','Google must discover a page<br>before it can show it in search.','SEO helps search engines access, understand and evaluate useful pages. It does not buy a position.',
        [('Crawl: find the page','Google follows links and reads sitemaps to discover URLs. Important product pages need accessible links and must not be blocked.'),('Index: understand the content','Clear text, page titles and consistent URLs help Google understand a page. Being indexed does not guarantee visibility.'),('Rank: answer the search','Google selects results for each query. Relevant, reliable content and a usable website support eligibility; competitors and intent also matter.')],diagram('How organic discovery works',['Discover the URL','Read and index content','Match a search query','Visitor chooses a result']),note='Source: Google Search Central · SEO Starter Guide')
    page('SEO / What we build','Match each search need<br>to a useful Mecosin page.','Build pages for real customer questions, not repeated keywords or unsupported health claims.',
        [('Product searches','A search for a named Mecosin product should reach ingredients, approved label details, warnings and a clear purchase option.'),('Partner searches','An English manufacturing or distribution page should explain verified capabilities, documents and how to send an enquiry.'),('Technical and editorial work','Provide mobile usability, descriptive titles, internal links and sitemaps. Review health content with qualified experts and keep it current.')],diagram('Pages matched to visitor needs',['Visitor searches','Products','Partnerships','Education','Relevant next step'],'branches'),note='Illustrative content plan · Keyword demand and claims require validation')
    page('SEO / Business benefits','Measure enquiries and sales,<br>not rankings alone.','SEO can bring people already searching for relevant information to the official website.',
        [('Business benefit','Official pages can answer questions before purchase, support brand trust and create routes to consumer sales or partner enquiries.'),('SEO and ads have different roles','Ads buy placements; organic listings have no per-click ad charge. SEO still costs time, content and maintenance; results can take months.'),('Measure the full journey','Use Search Console for impressions and clicks; analytics for enquiries and purchases. Compare qualified leads, conversion and revenue over time.')],diagram('Proposed measurement funnel',['Search impressions','Relevant website visits','Enquiries or purchases','Revenue and repeat orders']),note='No guaranteed rankings, traffic or revenue · Measurement setup required')
    page('04 / B2B & export','Show capabilities and documents<br>to support partner enquiries.','Bring capabilities, evidence and a clear contact path into one experience.',
        [('A verified trust center','Publish applicable BPOM, Halal, GMP, ISO and export documentation only after verification.'),('Capabilities made clear','Explain R&D, laboratory testing and manufacturing with substantiated information.'),('Materials ready to share','Offer a company profile, digital catalogues, multilingual pages and a concise partnership form.')],image('laboratory-large.webp','Laboratory photograph from Mecosin website assets','Existing Mecosin website photo · not proof of certification'))
    page('05 / Partnership models','Explain OEM, supply<br>and distribution options.','Help prospects recognise which business conversation fits their needs.',
        [('Private label / OEM / ODM','Dedicated information for contract manufacturing opportunities, if those services are available.'),('Raw materials and extracts','Explain supply specifications only where supported by actual capabilities.'),('International distribution','Clarify partner criteria, available territories and the first enquiry step.')],diagram('Alternative partnership routes',['Business requirements','OEM / ODM','Materials','Distribution','Relevant enquiry'],'branches'),note='Proposed models from the pitch · Availability requires confirmation')
    page('06 / B2B enquiry flow','AI live chat answers FAQs<br>and qualifies B2B enquiries.','Purpose: answer routine questions immediately and send the right business enquiries to the Mecosin team.',
        [('Answer recurring questions','Explain published capabilities, available documents and how to contact the team, using an approved knowledge base.'),('Collect useful enquiry details','Ask for company, country, product interest and requirements. With consent, pass a summary to Sales for follow-up.'),('Keep humans in charge','Sales confirms feasibility, price and lead time. AI must hand off unknown answers; it cannot provide medical advice or promise deals.')],diagram('Proposed B2B chat workflow',['Answer approved FAQs','Collect business requirements','Summarise + send to Sales','Human follow-up']),note='Proposed service · Measure response time, qualified enquiries and handoff completion')
    page('07 / Consumer experience','Help shoppers find products<br>and read approved information.','Start with the visitor’s needs, then provide clear and approved product information.',
        [('Needs-based discovery','Explore categories such as immunity, sleep or digestion. Product mapping requires qualified review.'),('Useful product explanations','Show ingredients, approved uses, label instructions and limitations.'),('Interactive product exploration','Consider ingredient views or 3D packaging for the website and marketplace channels.')],image('laserin-dewasa.webp','Laserin product packaging from the Mecosin catalogue','Real product asset · Interactive / 3D treatment proposed'),cls='product-slide')
    page('08 / Consumer insight','Answer product questions<br>before customers buy.','The pitch highlights the need for reassurance before buying health products.',
        [('People want explanations','Product descriptions should answer practical questions about information and use.'),('Personal questions need care','Generic descriptions may not resolve individual concerns. Clinical questions need qualified advice.'),('Use a helpful tone','Support the decision rather than pushing a purchase. This is a qualitative pitch insight, not validated survey data.')],'<figure class="visual-art chat-art"><span class="mock-label">ILLUSTRATIVE CONVERSATION</span><div class="bubble customer">Where can I find the product’s usage instructions?</div><div class="bubble assistant">I can help you find the approved label information.</div><div class="bubble customer">What about my personal health condition?</div><div class="bubble assistant">A doctor or pharmacist can advise on personal suitability.</div><figcaption>Scripted example · not a real customer conversation</figcaption></figure>',cls='statement')
    page('09 / AI product assistant','AI explains product labels;<br>clinicians advise on health.','Translate the “Personalized Health Advisor” idea into a safe product-information assistant.',
        [('Support approved information','Provide label-based details, verified registration information and reviewed general education.'),('Do not diagnose or guarantee safety','Do not match medication to symptoms or promise safety for GERD, drug interactions or personal conditions.'),('Escalate clinical questions','Route to a doctor or pharmacist. A proposed 24/7 service still needs oversight, privacy safeguards and operating budget.')],diagram('Safe response routing',['Visitor question','Approved product information?','Clinical or personal concern?','Refer to doctor / pharmacist']))
    page('10 / Brand education','Explain ingredients, sourcing<br>and testing with evidence.','Build trust through education and transparency rather than unsupported claims.',
        [('Herbal encyclopedia','Distinguish traditional use from benefits supported by clinical evidence.'),('Farm to capsule','Document sourcing, processing, R&D and testing with verifiable material.'),('Virtual access','Consider video or a 360° facility / farm tour for partners who cannot visit in person.')],image('botanical.webp','Botanical ingredients from Mecosin website assets','From ingredients to evidence · proposed educational journey'))
    page('11 / Brand credibility','Build trust with company history,<br>people and verified records.','Make the company’s experience and responsibilities easier to understand.',
        [('A documented legacy','Build a visual timeline from verified milestones, company records and awards.'),('Permission-based social proof','Curate reviews, video testimonials and healthcare-professional contributions with compliance review.'),('Sustainability and CSR','Publish substantiated stories about packaging, farming partners and community initiatives.')],image('team.webp','Team photograph from Mecosin website assets','Existing Mecosin team image · claims require supporting records'))
    page('12 / Owned commerce','Own store vs marketplaces:<br>control, reach and total cost.','Use Shopee, Tokopedia and TikTok Shop for discovery; develop the official store for brand control and repeat purchases.',
        [('Control the customer experience','Mecosin sets page content, bundles and loyalty rules. Consent-based customer records support direct service and repeat orders.'),('Keep marketplace strengths','Marketplaces offer shopping audiences, familiar checkout and platform tools. Visibility still depends on competition, ads and platform rules.'),('Compare profit, not commission alone','An own store still pays for acquisition, payments, technology, fulfilment and support. Launch alongside marketplaces; test margin and repeat orders.')],'<figure class="visual-art" style="padding:24px"><table style="width:100%;border-collapse:collapse;font-size:18px;line-height:1.3"><thead><tr><th style="text-align:left;padding:12px">Channel</th><th style="text-align:left;padding:12px">Own store</th><th style="text-align:left;padding:12px">Marketplaces</th></tr></thead><tbody>'+''.join('<tr>'+''.join('<td style="padding:10px 12px;border-top:1px solid #dce5dc;vertical-align:top">'+cell+'</td>' for cell in cells)+'</tr>' for cells in [('Reach','Build traffic via SEO, ads and existing customers','Existing shopping audiences; compete for attention'),('Experience','Control content, checkout and loyalty','Work within platform features and policies'),('Costs','Acquisition + operations + payment fees','Seller fees + ads/programs + operations'),('Relationships','Consent-based CRM and direct service','Customer engagement within platform rules')])+'</tbody></table><figcaption>Qualitative comparison · Seller fees vary by category, seller type and programme. No savings claim.</figcaption></figure>',note='Sources: Shopee Seller Education; Tokopedia & TikTok Shop Academy · Source links in README')
    page('Commerce / Customer benefits','Give customers a clear path<br>from product information to purchase.','An owned store connects official information, checkout and after-sales support in one place.',
        [('Explain before selling','Show approved label details, pack options, availability and full costs. Customers should know what they are buying before payment.'),('Make ordering dependable','Offer secure payment, delivery estimates, order confirmation and accessible support. Integrations and fulfilment must work before launch.'),('Support repeat purchases','Offer optional accounts, reorder links and useful bundles. Loyalty and reminders require consent and must not encourage inappropriate use.')],diagram('Proposed store journey',['Read approved information','Choose product and quantity','Pay and receive confirmation','Delivery, support and reorder']),note='Proposed commerce capabilities · Not active transactions in the preview')
    page('Commerce / Channel economics','An owned store is not free.<br>Compare total selling costs.', 'Lower marketplace commission alone does not prove that selling through the website is more profitable.',
        [('Marketplace costs','Check the applicable seller fees, ad spend, programme charges, discounts and fulfilment costs. Rates depend on category and seller terms.'),('Own-store costs','Budget for payment processing, traffic acquisition, hosting, maintenance, security, fulfilment, returns and customer support.'),('Decision rule','Compare net revenue after product cost and channel costs. Track acquisition cost and repeat orders; test real economics before scaling.')],diagram('Compare both channels equally',['Net sales after refunds','Less product and fulfilment costs','Less fees, marketing and service','Contribution toward fixed costs']),note='Framework only · No assumed fee rates or savings; allocate fixed operating costs separately')
    page('Commerce / Launch approach','Keep marketplaces for reach;<br>build direct sales alongside them.','Start with a manageable catalogue and a team that can fulfil and support every order.',
        [('Define the role of each channel','Keep marketplace discovery and familiar checkout. Use the official site for detailed education, brand experience and consent-based retention.'),('Prepare the operation','Assign owners for stock, payments, delivery, returns and customer data. Test failed payments, cancellations and refunds before launch.'),('Expand only with evidence','Review conversion, contribution, repeat purchase and service quality. Expand products and loyalty only when demand and operations support it.')],diagram('Proposed launch gates',['Confirm products and owners','Test payments and fulfilment','Launch a limited catalogue','Review results before expanding']),note='Channel strategy proposal · Respect marketplace policies and customer privacy')
    page('13 / Development priorities','Launch core pages first;<br>add chat and commerce in stages.','A proposed sequence for discussion, not a delivery timeline or budget commitment.',
        [('Foundation','Mobile-first journeys, product information, company/B2B pages and SEO structure.'),('Content and conversations','Verified documents, downloads, knowledge hub, enquiry forms and a bounded assistant.'),('Commerce and retention','Validate payment, fulfilment, service, loyalty and customer-data operations before expanding.')],diagram('Proposed implementation sequence',['01  Platform foundation','02  Content + conversations','03  Commerce + retention','Owner review at each stage']),note='Linc discussion sequence · Derived from the pitch')
    page('14 / Next discussion','Agree on goals, content owners<br>and the first delivery scope.','Choose the business result that matters most, then decide what is ready to build.',
        [('Business objective','B2B enquiries, consumer sales, brand awareness or direct customer relationships?'),('Content readiness','Product documentation, certifications, catalogue assets and qualified medical review.'),('Operational ownership','Assign owners for enquiries, content, customer service and transactions.')],diagram('Scope decision inputs',['Business goal','Content readiness','Team ownership','Agreed first scope']),note='Source: Mecosin – Platform Revamp Pitch',cls='closing')
